bms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('installations/', include('installations.urls')),
    ]

handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'
handler403 = 'users.views.error_403'

installations/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("location/", views.addLocation, name="location"),
    path('update/location/<int:pk>/', views.updateLocation, name='updateLocation'), 
    path('delete/location/<int:pk>/', views.deleteLocation, name='deleteLocation'),
    path('install/', views.installation, name='installation'),
    path('view/installation/<int:pk>/', views.viewInstallation, name='viewInstallation'), 
    path('view/installation/faulty/', views.faultyInstallation, name='faultyInstallation'), 
    path('update/installation/<int:pk>/', views.updateInstallation, name='updateInstallation'), 
    path('delete/installation/<int:pk>/', views.deleteInstallation, name='deleteInstallation'),
    path("report/", views.report, name="report"),
    path('report/update/<int:pk>/', views.updateReport, name='updateReport'), 
    path('report/delete/<int:pk>/', views.deleteReport, name='deleteReport'),
]

installations/models.py
from django.db import models
from users.models import CustomUser
from django.utils import timezone
from cloudinary.models import CloudinaryField

# Create your models here.


class Location (models.Model):
    STATE_CHOICE = 	(('S', '-----------'),('AB', 'Abia'), ('FCT',' FCT') , ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), 
                    ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), 
                    ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), 
                    ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), (
                    'SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara'))
    REGION_CHOICE = (('S', '-----------'),('ABJ1', 'ABUJA 1'), ('ABJ2', 'ABUJA 2'), ('AI', 'AGEGE IKORODU'), ('AP', 'APAPA'), ('AW', 'AWKA'), ('CRA', 'CROSS RIVER AKWA IBOM'), 
                    ('EE', 'ENUGU EBONYI'), ('FE', 'FESTAC'), ('IK', 'IKEJA'), ('IKL', 'IKOYI'), ('IA', 'IMO ABIA'), ('LI', 'LAGOS ISLAND'), ('MA1', 'MAINLAIN 1'), ('MA2', 'MAINLAIN 2'), 
                    ('MD1', 'MIDWEST 1'), ('MD2', 'MIDWEST 2'), ('NC', 'NORTH CENTRAL'), ('NE', 'NORTH EAST'), ('NW1', 'NORTH WEST 1'), ('NW2', 'NORTH WEST 2'), ('ON', 'ONITSHA'), 
                    ('RB1', 'RIVER BAYELSA 1'), ('RB2', 'RIVER BAYELSA 2'), ('SW1', 'SOUTH WEST 1'), ('SW2', 'SOUTH WEST 2'), ('VI', 'VICTORIA ISLAND'))
    clients = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    branch = models.CharField(blank=True, null=True, max_length=250)
    branch_id = models.CharField(blank=True, null=True,  max_length=15)
    cug_num1 = models.CharField(blank=True, null=True, max_length=14)
    cug_num2 = models.CharField(blank=True, null=True, max_length=14)
    state = models.CharField(null=False, blank=False, max_length=4, choices= STATE_CHOICE, default='S')
    address = models.CharField(blank=False, null=False, max_length=200)
    regional_office = models.BooleanField(default=False)
    region = models.CharField(max_length=5, choices=REGION_CHOICE, default='S')
    date_added = models.DateField(auto_now_add=True)

    def __str__ (self):
        return f'{self.branch_id} - {self.address}'
    
class Installation (models.Model):
    EQUIPMENT_CHOICE = (('S', 'Select Equipment'),('UPS', 'UPS'),('UB', 'UPS Battery'), ('PI', 'Power Inverter'), ('IB', 'Inverter Battery'), ('SP', 'Surge Protector'), ('PG', 'Power Generator'), ('VR', 'Voltage Regulator'),
                        ('BS', 'Bypass Switch'), ('SOP', 'Solar Panel'), ('OT', 'Others')
                        )
    STATUS_CHOICE = (('G', 'Good'), ('B', 'Bad'))
    LIFE_SPAN_CHOICE = (('NR', 'Not Rated'), ('1L', '1-2 Years'), ('2L', '2-3 Years'), ('3L', '3-4 Years'), ('4L', '4-5 Years'), ('5L', '5-6 Years'), ('6L', '6-7 Years'), ('7L', '7-8 Years'), 
                        ('8L', '8-9 Years'), ('9L', '9-10 Years'),  ('2kL', '2-4 Years'), ('4kL', '4-6 Years'), ('6kL', '6-8 Years'), ('8kL', '8-10 Years'), ('2YL', '20-25 Years'), ('5YL', '25-30 Years'), ('10YL', '30-35 Years'), ('OT', 'Others')) 
                        
    BRAND_CHOICE =(('S', 'Select Brand'),('S', '---------------- Battery Brands----------------'), ('AMARON', 'AMARON'), ('ARCCHAR', 'ARCCHAR'), ('DAYSTAR', 'DAYSTAR'), ('E.P', 'E.P'), ('EVER EXCEED', 'EVER EXCEED'), ('FELICITY', 'FELICITY'), ('G.P', 'G.P'), ('GASTON', 'GASTON'),
                    ('GENUS', 'GENUS'), ('HOPPECKE', 'HOPPECKE'), ('MECURY', 'MECURY'), ('MF', 'MF'), ('MONBAT', 'MONBAT'), ('MVR', 'MVR'), ('POWER PREM', 'POWER PREM'), ('POWER STAR', 'POWER STAR'), 
                    ('POWER V', 'POWER V'), ('PRIME SOLAR', 'PRIME SOLAR'), ('PROSTAR-LEMAX', 'PROSTAR-LEMAX'), ('QUANTA', 'QUANTA'), ('RITAR', 'RITAR'), ('SHOTO', 'SHOTO'), ('SURFIT', 'SURFIT'), 
                    ('TRATA', 'TRATA'), ('TROJAN SAGEM', 'TROJAN SAGEM'), ('TROJAN(SLIM)', 'TROJAN(SLIM)'), ('S', '---------------- Generator Brands ----------------'), ('C-POWER', 'C-POWER'), ('CUMMINS', 'CUMMINS'), ('FG WILSON', 'FG WILSON'), ('GHADDOR', 'GHADDOR'), ('HAT GLOBAL SP', 'HAT GLOBAL SP'),
                    ('JMG', 'JMG'), ('JOHN HOLT', 'JOHN HOLT'), ('JUBALLI', 'JUBALLI'), ('KHNEISSER HIJAZI', 'KHNEISSER HIJAZI'), ('MANTRAC', 'MANTRAC'), ('MARAPCO', 'MARAPCO'),('MARCOPOLO', 'MARCOPOLO'), 
                    ('MIKANO', 'MIKANO'), ('PERKINS', 'PERKINS'), ('S', '---------------- Inverter Brands ----------------'), ('AARCHOR', 'AARCHOR'),('BPC', 'BPC'),('COMP HC', 'COMP HC'),('EMERSON', 'EMERSON'),('ENDLESS POWER', 'ENDLESS POWER'),('ENERGIER', 'ENERGIER'),
                    ('FELICITY', 'FELICITY'),('FRONIOUS', 'FRONIOUS'),('GENNEX', 'GENNEX'),('INFORM', 'INFORM'),('IPOWER PLUS', 'IPOWER PLUS'),('KINERGIER PRO', 'KINERGIER PRO'),('LIEBERT', 'LIEBERT'),
                    ('MEGATECH', 'MEGATECH'),('MONEY POWER', 'MONEY POWER'),('MST SERIES', 'MST SERIES'),('NUMERIC', 'NUMERIC'),('OPTI-SOLAR', 'OPTI-SOLAR'),('POWER PRO', 'POWER PRO'),(
                        'POWERGEM PRO', 'POWERGEM PRO'),('POWERSINE', 'POWERSINE'),('PROSTAR', 'PROSTAR'),('SCHNEIDER', 'SCHNEIDER'),('SOROTEC', 'SOROTEC'), ('OT', 'Others'))
 

    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    equipment_type = models.CharField(null=False, blank=False, max_length=4, choices=EQUIPMENT_CHOICE, default='S')
    equipment_others = models.CharField(null=True, blank=True, max_length=120)
    quantity = models.IntegerField(default=1)
    life_span = models.CharField(choices=LIFE_SPAN_CHOICE, max_length=5, default='NR')
    brand_name = models.CharField(null=False, blank=False, choices=BRAND_CHOICE, max_length=90)
    brand_others = models.CharField(null=True, blank=True, max_length=120)
    technical_specification = models.CharField(null=False, blank=False, max_length=120)
    date_manufactured = models.DateField(null=True, blank=True)
    installation_date = models.DateField(blank=True, null=True)
    replacement_date = models.DateField(blank=True, null=True)
    contact_person = models.CharField(null=True, blank=True, max_length=150)
    equipment_status = models.CharField(null=False, blank=False, max_length=1, choices=STATUS_CHOICE, default='Good')
    engineer = models.ForeignKey(CustomUser, on_delete= models.SET_NULL, null=True, blank=True)
    remark = models.CharField(max_length=150)
    photo = CloudinaryField('image', null=True, blank=True)

    def __str__(self):
        return f'{self.get_equipment_type_display()}, {self.get_brand_name_display()}, {self.location.address}'

class Report (models.Model):
    engineer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    installation = models.ForeignKey(Installation, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    report = models.CharField(null=False, blank=False, max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.location.branch_id} - {self.Location.branch} - {self.report}'

installations/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib import messages
from .forms import LocationForm, InstallationForm, ReportForm
from .models import Location, Installation, Report

# Create your views here.
@login_required()
def addLocation (request):
    if request.user.is_password_changed: 
        form =  LocationForm()
        paginator = Paginator(Location.objects.all().order_by('-date_added'), 30)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        if request.method == 'POST':
            form = LocationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Added: Location has been added')
                return redirect ('location')
        context = {
            'form': form, 
            'locations': Location.objects.all(),
            'page_obj': page_obj,
        }
        return render (request, 'installations/location.html', context)
    else:
        return redirect('change-password')

@login_required()    
def updateLocation (request, pk):
    if request.user.is_password_changed:
        location = Location.objects.get(id=pk)
        form = LocationForm(instance = location)
        if request.method == 'POST':
            l_form = LocationForm(request.POST, instance = location)
            if l_form.is_valid():
                l_form.save()
                messages.success(request, 'Update: Location has been updated')
                return redirect('location')
        context = {
            'form': form, 
            'installations':Installation.objects.filter(location=location),
            "reports": Report.objects.filter(location=location)
        }
        return render(request, 'installations/location_update.html', context)
    else:
        return redirect('change-password')


@login_required()
def deleteLocation (request, pk):
    if request.user.is_password_changed:
        location = Location.objects.get(pk=pk)
        location.delete()
        messages.success(request, 'Deleted: Location has been deleted')
        return redirect('location')
    else:
        return redirect('change-password')

@login_required()
def installation(request):
    if request.user.is_password_changed:
        form = InstallationForm()
        info = Installation.objects.all()
        paginator = Paginator(Installation.objects.all().order_by('-installation_date'), 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        if request.method == 'POST':
            form = InstallationForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Added: Installation has been added')
                return redirect('installation')
        context = {
            'form': form, 
            'installations': Installation.objects.all(),
            'page_obj': page_obj,
        }
        return render(request, 'installations/installation.html', context)
    else:
        return redirect('change-password')

@login_required()
def updateInstallation(request, pk):
    if request.user.is_password_changed:
        form = InstallationForm(instance=Installation.objects.get(pk=pk))
        if request.method == 'POST':
            i_form = InstallationForm(request.POST, request.FILES, instance=Installation.objects.get(pk=pk))
            if i_form.is_valid():
                i_form.save()
                messages.success(request, 'Updated: Installation has been updated')
                return redirect('installation')
        context = { 
            'form': form,
            'reports': Report.objects.filter(installation=Installation.objects.get(pk=pk)),
            }
        return render(request, 'installations/installation_update.html', context)
    else:
        return redirect('change-password')

@login_required()
def viewInstallation(request, pk):
    if request.user.is_password_changed:
        installation = Installation.objects.get(pk=pk)
        context = { 
            'installation': installation,
            }
        return render(request, 'installations/installation_view.html', context)
    else:
        return redirect('change-password')

def faultyInstallation(request):
    paginator = Paginator(Installation.objects.filter(equipment_status = 'B').order_by('-installation_date'), 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
        'installations': Installation.objects.filter(equipment_status = 'B')
    }
    return render (request, 'installations/faulty_installation.html', context)

@login_required()
def deleteInstallation (request, pk):
    if request.user.is_password_changed:
        installation = Installation.objects.get(pk=pk)
        installation.delete()
        messages.success(request, 'Deleted: Installation has been deleted')
        return redirect('installation')
    else:
        return redirect('change-password')


@login_required()
def report(request):
    if request.user.is_password_changed:
        form = ReportForm()
        paginator = Paginator(Report.objects.all().order_by('-date'), 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        if request.method == 'POST':
            form = ReportForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Added: Report has been added')
                return redirect('report')
        context = {
            'form': form, 
            'reports': Report.objects.all(),
            'page_obj': page_obj,
        }
        return render(request, 'installations/report.html', context)
    else:
        return redirect('change-password')

@login_required()
def updateReport(request, pk):
    if request.user.is_password_changed:
        form = ReportForm(instance=Report.objects.get(pk=pk))
        if request.method == 'POST':
            i_form = ReportForm(request.POST, instance=Report.objects.get(pk=pk))
            if i_form.is_valid():
                i_form.save()
                messages.success(request, 'Updated: Report has been updated')
                return redirect('report')
        context = { 'form': form}
        return render(request, 'installations/report_update.html', context)
    else:
        return redirect('change-password')

@login_required()
def deleteReport (request, pk):
    if request.user.is_password_changed:
        report = Report.objects.get(pk=pk)
        report.delete()
        messages.success(request, 'Deleted: Report has been deleted')
        return redirect('report')
    else:
        return redirect('change-password')

installations/templates/installations/faulty_installation.html
{% extends "users/layouts/base.html" %} {% load static %}

{% block title %} Faulty Installation {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <button class="btn btn-sm btn-primary pull-right" onclick="history.back()"> <span class="material-icons">
      arrow_back
      </span></button>
  </div>
</div> 
        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title">Faulty Installations</h4>
                  <p class="card-category"> Installation Info</p>
                </div>
                <div class="card-body">
                  <input type="text" class="form-control" id="search" placeholder="Type to search">
                  <div class="table-responsive">
                    <table class="table" id='installation-table'>
                      <thead class=" text-primary">
                        <th>
                          SOL ID
                        </th>
                        <th>
                          Equipment Type
                        </th>
                        <th>
                          Quantity
                        </th>
                        <th>
                          Brand Name
                        </th>
                        <th>
                          Specification
                        </th>
                        <th>
                          Installation Date
                        </th>
                        <th>
                          Manufacture Date
                        </th>
                        <th>
                          Replacement Date
                        </th>
                        <th>
                          Life Span
                        </th>
                       <th>
                          Vendor Contact
                        </th>
                        <th>
                          Status
                        </th>
                        <th>
                         Remark
                        </th>
                        <th>
                          photo
                        </th>
                        <th>
                          Actions
                        </th>
                      </thead>
                      <tbody>
                        {% for installation in installations %}  
                        <tr>
                          <td>
                            {{ installation.location.branch_id }}
                          </td>
                          <td>
                            {{ installation.get_equipment_type_display }}
                          </td>
                          <td>
                            {{ installation.quantity }}
                          </td>
                          <td>
                            {% if installation.brand_name != 'none' %}
                            {{ installation.get_brand_name_display }}
                            {% else %}
                            {{ installation.brand_others}}
                            {% endif %} 
                          </td>
                          <td>
                            {{ installation.technical_specification }} 
                          </td>
                          <td>
                            {{ installation.installation_date }}
                          </td>
                          <td>
                            {{ installation.date_manufactured }}
                          </td>
                          <td>
                            {{ installation.replacement_date }}
                          </td>
                          <td>
                            {{ installation.get_life_span_display}}
                          </td>
                          <td>
                            {{ installation.contact_person }}
                          </td>
                          <td>
                            {{ installation.get_equipment_status_display }}
                          </td>
                          <td>
                            {{ installation.remark }}
                          </td>
                          <td>
                           {% if installation.photo %}
                           <a target="_blank" href="{{ installation.photo.url }}"> view photo</a>
                           {% else %}
                           No Image
                           {% endif %} 
                          </td>
                          <td>
                            <a href="{% url 'viewInstallation' installation.id %}"  class="btn btn-sm btn-primary" >
                              <span class="fa fa-eye"> </span>
                            <a href="{% url 'updateInstallation' installation.id %}"  class="btn btn-sm btn-primary" >
                              <span class="fa fa-pencil"></span>
                            </a> | <a href="{% url 'deleteInstallation' installation.id %}" class="btn btn-sm btn-primary" >
                              <span class="fa fa-trash"></span>
                            </a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  <div class="pagination-area d-flex flex-wrap justify-content-between align-items-center">
                    <div class="pagination-cont">
                        Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </div>
                    <ul class="pagination">
                        <li>
                            {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a> {% endif %}
                        </li>
                        <li>
                            <a href="?page={{ page_obj.number }}" class="active">{{ page_obj.number }} </a>
                        </li>
                        <li>
                            {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endif %}
                        </li>
                    </ul>
                </div>
                </div>
              </div>
            </div>
        </div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>
  var $rows = $('#installation-table tr');
$('#search').keyup(function() {
    var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase();
    
    $rows.show().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        return !~text.indexOf(val);
    }).hide();
});

</script>
{% endblock javascripts %}

installations/templates/installations/installation_view.html
{% extends "users/layouts/base.html" %}
{% load static %}
{% block title %} Report Update {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <button class="btn btn-sm btn-primary pull-right" onclick="history.back()"> <span class="material-icons">
      arrow_back
      </span></button>
  </div>
</div>  
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">{{ installation.location.branch }} - Branch Code: {{ installation.location.branch_id }}</h4>
        <p class="card-category"> {{ installation.location.address }}</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table" id='report-table'>
            <thead class=" text-primary">
              <th>
                Parameters
              </th>
              <th>
                Installation Details
              </th>
            </thead>
            <tbody>
              <tr>
                <td>
                  Equipment Type
                </td>
                <td>
                  {{ installation.get_equipment_type_display }}
                </td>
              </tr>
              <tr>
                <td>
                  Quantity
                </td>
                <td>
                  {{ installation.quantity }}
                </td>
              </tr>
              <tr>
                <td>
                  Brand Name
                </td>
                <td>
                  {% if installation.brand_name != '0T' %}
                      {{ installation.get_brand_name_display }}
                  {% else %}
                      {{ installation.brand_others }}
                  {% endif %} 
                </td>
              </tr>
              <tr>
                <td>
                  Technical Specification
                </td>
                <td>
                  {{ installation.technical_specification }}
                </td>
              </tr>
              <tr>
                <td>
                  Installation Date
                </td>
                <td>
                  {{ installation.installation_date }}
                </td>
              </tr>
                <td>
                  Manufacture Date
                </td>
                <td>
                  {{ installation.date_manufactured}}
                </td>
              </tr>
              <tr>
                <td>
                  Replacement Date
                </td>
                <td>
                  {{ installation.replacement_date }}
                </td>
              </tr>
              <tr>
                <td>
                  Life Span
                </td>
                <td>
                  {{ installation.get_life_span_display }}
                </td>
              </tr>
              <tr>
                <td>
                  Contact Person
                </td>
                <td>
                  {{ installation.contact_person }}
                </td>
              </tr>
              <tr>
                <td>
                  Equipment Status
                </td>
                <td>
                  {{ installation.get_equipment_status_display }}
                </td>
              </tr>
              <tr>
                <td>
                  Remark
                </td>
                <td>
                  {{ installation.remark}}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <img src="{{ installation.photo.url }}" height=500 width=500 alt="{{ installation.get_equipment_type_display}}">
  </div>
</div>





{% endblock content %}

{% block javascripts %}

{% endblock javascripts %}

installations/templates/installations/report_update.html
{% extends "users/layouts/base.html" %}
{% load static %}
{% block title %} Report Update {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Update Report</h4>
        <p class="card-category">Report details</p>
      </div>
      <div class="card-body">
        {% if form.errors %}
          <div class="alert alert-warning" role="alert">
              {{ form.errors }}
          </div>
          {% endif %}
        <form method="post">  
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label class="bmd-label-floating">Location</label>
                {{ form.location }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label class="bmd-label-floating">Report</label>
                {{ form.report }}
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary pull-right">Update Report</button>
          <div class="clearfix"></div>
        </form>
      </div>
    </div>
  </div>
</div>





{% endblock content %}

{% block javascripts %}

{% endblock javascripts %}