bms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500, handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('installations/', include('installations.urls')),
    ]

handler404 = 'users.views.error_404'
handler500 = 'users.views.error_500'
handler403 = 'users.views.error_403'

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.userLogin, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('clients/', views.clients, name='clients'),
    path('change-password/', views.changePassword, name='change-password'),
    path('user/update/<int:pk>/', views.userUpdate, name='userupdate'), 
    path('user/delete/<int:pk>/', views.deleteUser, name='deleteuser'),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='users/home/password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='users/home/password_reset_done.html'), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name='users/home/password_reset_confirm.html'), name="password_reset_confirm"),
    path("password-reset-complete/done/", auth_views.PasswordResetCompleteView.as_view(template_name = 'users/home/password_reset_complete.html'), name="password_reset_complete"),
]

installations/models.py
from django.db import models
from users.models import CustomUser
from django.utils import timezone
from cloudinary.models import CloudinaryField

# Create your models here.


class Location (models.Model):
    STATE_CHOICE = 	(('S', '-----------'),('AB', 'Abia'), ('FCT',' FCT') , ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), 
                    ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), 
                    ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), 
                    ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), (
                    'SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara'))
    REGION_CHOICE = (('S', '-----------'),('ABJ1', 'ABUJA 1'), ('ABJ2', 'ABUJA 2'), ('AI', 'AGEGE IKORODU'), ('AP', 'APAPA'), ('AW', 'AWKA'), ('CRA', 'CROSS RIVER AKWA IBOM'), 
                    ('EE', 'ENUGU EBONYI'), ('FE', 'FESTAC'), ('IK', 'IKEJA'), ('IKL', 'IKOYI'), ('IA', 'IMO ABIA'), ('LI', 'LAGOS ISLAND'), ('MA1', 'MAINLAIN 1'), ('MA2', 'MAINLAIN 2'), 
                    ('MD1', 'MIDWEST 1'), ('MD2', 'MIDWEST 2'), ('NC', 'NORTH CENTRAL'), ('NE', 'NORTH EAST'), ('NW1', 'NORTH WEST 1'), ('NW2', 'NORTH WEST 2'), ('ON', 'ONITSHA'), 
                    ('RB1', 'RIVER BAYELSA 1'), ('RB2', 'RIVER BAYELSA 2'), ('SW1', 'SOUTH WEST 1'), ('SW2', 'SOUTH WEST 2'), ('VI', 'VICTORIA ISLAND'))
    clients = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    branch = models.CharField(blank=True, null=True, max_length=250)
    branch_id = models.CharField(blank=True, null=True,  max_length=15)
    cug_num1 = models.CharField(blank=True, null=True, max_length=14)
    cug_num2 = models.CharField(blank=True, null=True, max_length=14)
    state = models.CharField(null=False, blank=False, max_length=4, choices= STATE_CHOICE, default='S')
    address = models.CharField(blank=False, null=False, max_length=200)
    regional_office = models.BooleanField(default=False)
    region = models.CharField(max_length=5, choices=REGION_CHOICE, default='S')
    date_added = models.DateField(auto_now_add=True)

    def __str__ (self):
        return f'{self.branch_id} - {self.address}'
    
class Installation (models.Model):
    EQUIPMENT_CHOICE = (('S', 'Select Equipment'),('UPS', 'UPS'),('UB', 'UPS Battery'), ('PI', 'Power Inverter'), ('IB', 'Inverter Battery'), ('SP', 'Surge Protector'), ('PG', 'Power Generator'), ('VR', 'Voltage Regulator'),
                        ('BS', 'Bypass Switch'), ('SOP', 'Solar Panel'), ('OT', 'Others')
                        )
    STATUS_CHOICE = (('G', 'Good'), ('B', 'Bad'))
    LIFE_SPAN_CHOICE = (('NR', 'Not Rated'), ('1L', '1-2 Years'), ('2L', '2-3 Years'), ('3L', '3-4 Years'), ('4L', '4-5 Years'), ('5L', '5-6 Years'), ('6L', '6-7 Years'), ('7L', '7-8 Years'), 
                        ('8L', '8-9 Years'), ('9L', '9-10 Years'),  ('2kL', '2-4 Years'), ('4kL', '4-6 Years'), ('6kL', '6-8 Years'), ('8kL', '8-10 Years'), ('2YL', '20-25 Years'), ('5YL', '25-30 Years'), ('10YL', '30-35 Years'), ('OT', 'Others')) 
                        
    BRAND_CHOICE =(('S', 'Select Brand'),('S', '---------------- Battery Brands----------------'), ('AMARON', 'AMARON'), ('ARCCHAR', 'ARCCHAR'), ('DAYSTAR', 'DAYSTAR'), ('E.P', 'E.P'), ('EVER EXCEED', 'EVER EXCEED'), ('FELICITY', 'FELICITY'), ('G.P', 'G.P'), ('GASTON', 'GASTON'),
                    ('GENUS', 'GENUS'), ('HOPPECKE', 'HOPPECKE'), ('MECURY', 'MECURY'), ('MF', 'MF'), ('MONBAT', 'MONBAT'), ('MVR', 'MVR'), ('POWER PREM', 'POWER PREM'), ('POWER STAR', 'POWER STAR'), 
                    ('POWER V', 'POWER V'), ('PRIME SOLAR', 'PRIME SOLAR'), ('PROSTAR-LEMAX', 'PROSTAR-LEMAX'), ('QUANTA', 'QUANTA'), ('RITAR', 'RITAR'), ('SHOTO', 'SHOTO'), ('SURFIT', 'SURFIT'), 
                    ('TRATA', 'TRATA'), ('TROJAN SAGEM', 'TROJAN SAGEM'), ('TROJAN(SLIM)', 'TROJAN(SLIM)'), ('S', '---------------- Generator Brands ----------------'), ('C-POWER', 'C-POWER'), ('CUMMINS', 'CUMMINS'), ('FG WILSON', 'FG WILSON'), ('GHADDOR', 'GHADDOR'), ('HAT GLOBAL SP', 'HAT GLOBAL SP'),
                    ('JMG', 'JMG'), ('JOHN HOLT', 'JOHN HOLT'), ('JUBALLI', 'JUBALLI'), ('KHNEISSER HIJAZI', 'KHNEISSER HIJAZI'), ('MANTRAC', 'MANTRAC'), ('MARAPCO', 'MARAPCO'),('MARCOPOLO', 'MARCOPOLO'), 
                    ('MIKANO', 'MIKANO'), ('PERKINS', 'PERKINS'), ('S', '---------------- Inverter Brands ----------------'), ('AARCHOR', 'AARCHOR'),('BPC', 'BPC'),('COMP HC', 'COMP HC'),('EMERSON', 'EMERSON'),('ENDLESS POWER', 'ENDLESS POWER'),('ENERGIER', 'ENERGIER'),
                    ('FELICITY', 'FELICITY'),('FRONIOUS', 'FRONIOUS'),('GENNEX', 'GENNEX'),('INFORM', 'INFORM'),('IPOWER PLUS', 'IPOWER PLUS'),('KINERGIER PRO', 'KINERGIER PRO'),('LIEBERT', 'LIEBERT'),
                    ('MEGATECH', 'MEGATECH'),('MONEY POWER', 'MONEY POWER'),('MST SERIES', 'MST SERIES'),('NUMERIC', 'NUMERIC'),('OPTI-SOLAR', 'OPTI-SOLAR'),('POWER PRO', 'POWER PRO'),(
                        'POWERGEM PRO', 'POWERGEM PRO'),('POWERSINE', 'POWERSINE'),('PROSTAR', 'PROSTAR'),('SCHNEIDER', 'SCHNEIDER'),('SOROTEC', 'SOROTEC'), ('OT', 'Others'))
 

    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    equipment_type = models.CharField(null=False, blank=False, max_length=4, choices=EQUIPMENT_CHOICE, default='S')
    equipment_others = models.CharField(null=True, blank=True, max_length=120)
    quantity = models.IntegerField(default=1)
    life_span = models.CharField(choices=LIFE_SPAN_CHOICE, max_length=5, default='NR')
    brand_name = models.CharField(null=False, blank=False, choices=BRAND_CHOICE, max_length=90)
    brand_others = models.CharField(null=True, blank=True, max_length=120)
    technical_specification = models.CharField(null=False, blank=False, max_length=120)
    date_manufactured = models.DateField(null=True, blank=True)
    installation_date = models.DateField(blank=True, null=True)
    replacement_date = models.DateField(blank=True, null=True)
    contact_person = models.CharField(null=True, blank=True, max_length=150)
    equipment_status = models.CharField(null=False, blank=False, max_length=1, choices=STATUS_CHOICE, default='Good')
    engineer = models.ForeignKey(CustomUser, on_delete= models.SET_NULL, null=True, blank=True)
    remark = models.CharField(max_length=150)
    photo = CloudinaryField('image', null=True, blank=True)

    def __str__(self):
        return f'{self.get_equipment_type_display()}, {self.get_brand_name_display()}, {self.location.address}'

class Report (models.Model):
    engineer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    installation = models.ForeignKey(Installation, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    report = models.CharField(null=False, blank=False, max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.location.branch_id} - {self.Location.branch} - {self.report}'

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    USER_OPTION = (("C", "Client"),("E", "Engineer"), ("S", "Staff"))
    email = models.EmailField(_('email address'), unique=True, max_length=60)
    first_name = models.CharField(null=True, blank=True, max_length=60)
    last_name = models.CharField(null=True, blank=True, max_length=60)
    address = models.CharField(null=True, blank=True, max_length=250)
    business_name = models.CharField(null=True, blank=True, max_length=200)
    user_status = models.CharField(max_length=22, choices=USER_OPTION, default="Client")
    phone_number = models.CharField(null=True, blank=True, unique=True, max_length=14)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name="Date joined")
    last_login = models.DateTimeField(auto_now=True, verbose_name="Last login")
    is_password_changed = models.BooleanField(default = False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return f'{self.first_name} - {self.last_name} - {self.email}'
    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_staff

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

users/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from installations.models import Location, Installation, Report
from .tasks import send_registration_email_task
from django.db.models.functions import TruncMonth
from django.db.models import Count

# Create your views here.
@login_required()
def index(request):
    if request.user.is_password_changed:
        info = Installation.objects.annotate(month=TruncMonth('installation_date')).values('month').annotate(c=Count('id')).order_by('month')
        context = {
            'clients': CustomUser.objects.filter(user_status='C').count(),
            'locations': Location.objects.all().count(),
            'report': Report.objects.all().count(),
            'faulty_installations': Installation.objects.filter(equipment_status = 'B').count(),
            'staffs': CustomUser.objects.filter(user_status='S').count(),
            'installations': Installation.objects.all().order_by('-installation_date')[:5],
            'locations_all': Location.objects.all().order_by('-date_added')[:5],
            'UPS' : Installation.objects.filter(equipment_type = 'UPS').count(),  
            'UPS_Battery': Installation.objects.filter(equipment_type = 'UB').count(),  
            'Power_Inverter': Installation.objects.filter(equipment_type = 'PI').count(),  
            'Power_Inverter_Battery': Installation.objects.filter(equipment_type = 'IB').count(), 
            'Surge_Protector': Installation.objects.filter(equipment_type = 'SP').count(),  
            'Power_Generator': Installation.objects.filter(equipment_type = 'PG').count(), 
            'Voltage_Regulator ': Installation.objects.filter(equipment_type = 'VR').count(), 
            'Bypass_Switch': Installation.objects.filter(equipment_type = 'BS').count(),  
            'Solar_Panel ': Installation.objects.filter(equipment_type = 'SOP').count(),  
            'Others': Installation.objects.filter(equipment_type = 'OT').count(), 
            'info':info,
        }
        return render(request, 'users/home/index.html', context)
    else:
        return redirect('change-password')

@login_required()
def clients(request):
    if request.user.is_password_changed:
        form = CustomUserCreationForm()
        users = CustomUser.objects.all()
        paginator = Paginator(CustomUser.objects.all().order_by('-date_joined'), 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "New user has been created")
                email = form.cleaned_data.get('email')
                password = form.cleaned_data.get('password1')
                first_name = form.cleaned_data.get('first_name')
                send_registration_email_task.delay(email, password, first_name)
                return redirect('clients')
        context = {
            'form':form, 
            'users':users,
            'page_obj': page_obj,
            }
        return render(request, 'users/home/page-user.html', context)
    else:
        return redirect('change-password')

@login_required()
def userUpdate(request, pk):
    form = CustomUserChangeForm(instance = CustomUser.objects.get(pk=pk))
    if request.method == 'POST':
        p_form =  CustomUserChangeForm(request.POST, instance = CustomUser.objects.get(pk=pk))
        if p_form.is_valid():
            p_form.save()
            messages.success(request, 'User update was successful')
            return redirect('clients')
    context = {
        'form': form, 
        'locations': Location.objects.filter(clients=CustomUser.objects.get(pk=pk))
    }
    return render(request, 'users/home/user-update.html', context)

@login_required()    
def deleteUser(request, pk):
    user = CustomUser.objects.get(pk=pk)
    user.delete()
    messages.success(request, 'User was deleted successfully')
    return redirect('clients')


def userLogin (request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                if request.user.is_password_changed:
                    return redirect('index')
                else:
                    return redirect('change-password')
            else:
                messages.error(request, "invalid User detail")
                return render(request, 'users/home/login.html')
    return render(request, 'users/home/login.html')


@login_required()
def changePassword (request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user = request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Password Changed Successfullly')
            user = CustomUser.objects.get(pk=request.user.id)
            user.is_password_changed = True
            user.save()
            return redirect ('index')
        messages.info(request, "Invalid password")
        return redirect ('change-password')
    else:
        context = {
            "form": PasswordChangeForm(user=request.user)
        }
        return render(request, 'users/home/change-password.html', context) 

def userLogout(request):
    logout(request)
    return redirect('login')

def error_404(request, exception):
    return render(request, '404.html')

def error_500(request, exception=None):
    return render(request, '500.html')

def error_403(request, exception=None):
    return render(request, '403.html')

users/templates/users/home/index.html
{% extends "users/layouts/base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.1/dist/chart.min.js"></script>
{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <!-- <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">content_copy</i>
            </div>
            <p class="card-category">Total Clients</p>
            <h3 class="card-title">{{ clients }}
              <small></small>
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-info">people</i>
              <a href="{% url 'clients' %}">View Clients</a>
            </div>
          </div>
        </div>
      </div> -->
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">store</i>
            </div>
            <p class="card-category">Locations</p>
            <h3 class="card-title">{{ locations }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">location_on</i> 
               <a href="{% url 'location' %}">View Locations</a> 
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons">info_outline</i>
            </div>
            <p class="card-category">Faulty Installation</p>
            <h3 class="card-title">{{ faulty_installations }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> 
              <a href="{% url 'faultyInstallation' %} ">View Installations</a> 
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              <i class="material-icons"> groups</i>
            </div>
            <p class="card-category">Employees</p>
            <h3 class="card-title">{{ staffs }}</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">people</i> 
              Number of Staff
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">summarize</i>
            </div>
            <p class="card-category">Reports</p>
            <h3 class="card-title">{{ report }}
              <small></small>
            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-info">summarize</i>
              <a href="{% url 'report' %}">View Reports</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-12">
        <div class="card">
          <div class="card-header card-header-tabs card-header-primary">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <span class="nav-tabs-title">Showing the total count of Installation Equipment Types</span>
              </div>
            </div>
          </div>
          <div class="card-body">
            <canvas id="chart" ></canvas>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title"></h4>
            <p class="card-category">Total Installation by Months</p>
          </div>
          <div class="card-body ">
            <canvas id="chart1" ></canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Location</h4>
            <p class="card-category"> Last 5 Added Locations</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <th> Branch</th>
                <th> SOL ID</th>
                <th>State</th>
                <th>Address</th>
                <th>Region</th>
              </thead>
              <tbody>
                
                {% for l in locations_all  %}
                  <tr>
                  <td>{{ l.branch }}</td>
                  <td>{{ l.branch_id }}</td>
                  <td>{{ l.get_state_display }}</td>
                  <td>{{ l.address }}</td>
                  <td>{{ l.get_region_display }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title"> Installations</h4>
            <p class="card-category">Last 5 Installations</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <th>Branch</th>
                <th>Equipment_Name</th>
                <th>Brand</th>
                <th>Equipment Status</th>
                <th>Quantity</th>
                <th>Installation Date</th>
              </thead>
              <tbody>
                
                {% for i in installations  %}
                  <tr>
                  <td>{{ i.location.branch }}</td>
                  <td>{{ i.get_equipment_type_display }}</td>
                  <td> {% if i.brand_name == '0T' %}
                    {{ i.brand_others }} {% else %} {{ i.get_brand_name_display }}
                  {% endif %} </td>
                  <td>{{ i.get_equipment_status_display }}</td>
                  <td>{{ i.quantity }}</td>
                  <td>{{ i.installation_date }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <script>
                  const ct = document.getElementById('chart').getContext('2d');
                  const chart = new Chart(ct, {
                      type: 'bar',
                      data: {
                          labels: ['UPS', 'UPS Battery', 'Power Inverter', 'Power Inverter Battery', 'Surge Protector', 'Power Generator', 
                                    'Voltage Regulator', 'Bypass Switch', 'Solar Panel', 'Others'],
                          datasets: [{
                              label: 'Total of Installation Equipment Type',
                              data: ['{{ UPS }}', '{{ UPS_Battery }}', '{{ Power_Inverter }}','{{ Power_Inverter_Battery }}', 
                                    '{{ Surge_Protector }}', '{{ Power_Generator }}', '{{ Voltage_Regulator }}', '{{ Bypass_Switch }}', '{{ Solar_Panel }}', '{{ Others }}'],
                              backgroundColor: [
                                  'rgba(54, 162, 235, 0.2)',
                              ],
                              borderColor: [
                                  'rgba(54, 162, 235, 1)',
                              ],
                              borderWidth: 1
                          }]
                      },
                      options: {
                          responsive: true,
                          scales: {
                              y: {
                                  beginAtZero: true
                              }
                          }
                      }
                  });
                  const ctx = document.getElementById('chart1').getContext('2d');
                  const chart1 = new Chart(ctx, {
                      type: 'line',
                      data: {
                          labels: [{% for i in info %} '{{ i.month }}', {% endfor %}],
                          datasets: [{
                              label: 'Total Installation',
                              data: [{% for i in info %} {{ i.c }}, {% endfor %}],
                              backgroundColor: [
                                  'rgba(255, 99, 132, 0.2)',
                                 
                              ],
                              borderColor: [
                                  'rgba(255, 99, 132, 1)',
                                  
                              ],
                              borderWidth: 1
                          }]
                      },
                      options: {
                          responsive: true,
                          scales: {
                              y: {
                                  beginAtZero: true
                              }
                          }
                      }
                  });
    </script>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

users/templates/users/home/password_reset.html
{% extends "users/layouts/base.html" %}

{% block title %} Password Reset Done{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
              Password Reset
          </h4>
        </div>
        <div class="card-body">

          <h5 class="card-category">
            An email will be sent to your email address follow the link to complete password reset.
            N/B: Check your Junk or Spam folder 
          </h5>
          <br/>
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label class="bmd-label-floating">Email</label>
              <input type="email" name="email" autocomplete="email"  class='form-control' required id="id_email"> 
             <div class='form-control-static'> {{ form.email.help_text }} </div>
             <button type="submit" name="password_Reset" class="btn btn-primary pull-left mt-4">Reset Password</button>
          </form>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

users/templates/users/home/password_reset_complete.html
{% extends "users/layouts/base.html" %}

{% block title %} Password Reset Completed {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Password Reset Completed
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              Your new password has been successfully entered
          </h6>
          <br />
              
          <span><a href="{% url 'login' %}"><button type="button" name="login" class="btn btn-primary pull-left">Login</button></a> <i class="flaticon-right-arrow"></i></span> 
            <div class="clearfix"></div>
          
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}